# Domain name
baseurl: ''
url: 'https://www.kiltandcode.com'

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:year/:month/:day/:title/
plugins: [jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customize atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           'Kilt and Code'
description:	       'A personal website by Steven McLintock'
author:              'Steven McLintock'