# Site Build Settings

# Domain name
baseurl:            ''
url:                'https://www.kiltandcode.com'

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:year/:month/:day/:title/
plugins:             [jekyll-sitemap, jekyll-feed, jekyll-seo-tag, jekyll-paginate]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           'Kilt & Code'
description:	       'A blog by Steven McLintock'
author:              'Steven McLintock'

# Pagination
paginate:             5
paginate_path:        '/page:num/'
