# If you are not using Google Analytics, 
# please change to an empty string
google-analytics: 'UA-140918235-1'

# The primary language used by this website
language: 'en'

# Favicon and icons for iOS etc.
apple-touch-icon: '/apple-touch-icon.png'
favicon-32: '/favicon-32x32.png'
favicon-16: '/favicon-16x16.png'
site-manifest: '/site.webmanifest'

# If you are not using a motif, 
# please set each value as an empty string
motif:
  src: '/assets/img/cartoon-scottish-face.png'
  width: '83'
  height: '90'

# Header menu
header-menu:
- { name: 'About', url: '/about' }
- { name: 'Articles', url: '/articles' }

# Footer menu
footer-menu:
- { name: 'Home', url: '/' }
- { name: 'About', url: '/about' }
- { name: 'Articles', url: '/articles' }
- { name: 'RSS', url: '/feed.xml' }

# About the author
about-the-author:
  name: 'Steven McLintock'
  src: '/assets/img/me-small.jpg'
  width: '100'
  height: '100'
  caption: 'Kilt and Code is the personal website of 
  ..<a href="/about">Steven McLintock</a>, a 
  ..Scottish software developer living in 
  ..Stratford, Ontario. Steven primarily uses 
  ..<a href="https://dotnet.microsoft.com/">.NET</a>, 
  ..C# and <a href="https://angular.io/">Angular</a> 
  ..and has been working as a developer since 2006. 
  ..<a href="mailto:stevenmclintock@fastmail.com">Get in touch!</a>'